language: ruby
rvm:
- 2.4.1
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake --trace db:create
- RAILS_ENV=test bundle exec rake --trace db:migrate
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
- bundle exec rubocop --config .rubocop.yml
deploy:
  provider: heroku
  app: infinite-loops-chess
  api_key:
    secure: "YDr7oHqZ0JRErYoqsJid6qQCQqLZKNMofeK7vNHBmE6NcOhBwpTFJNzGNbRP7+DWWPLrczsWhYlTYR8oqTe/GtMXKQae0UANb2+BOQ29pkjho57iRWImn4p5u3TLxeks3OEJbCPQrCA2Mtzpbu5k5eyjT2x2U1JEcD4NyD7Dd6nZ/4afjBS7wgyI0k9p7NJy2noj8ar6SM5Psfq2Ydz05FCPURmlSSWkmEFmtq/mod9KTti9bu/OWqI9vExPibNljQIaxps1jLCMDGb7GVvUUY/Iq/M9NFLasxhbMmPnZZDyMUOL5nmjCyFCupsrX2Z6X18dPncWKxXugwnsz1BPY+xH6zuI+geQVU1sieanuh3okYTu/TP+iaXkHqKN3FzQ5uB6ZDb84rMwxKO3uK4xRSA3VKrMrvQM0JAs6Fx7VVHlN2jkKMfEiR8NwTrmWd8EU7IPENktib3j7qMLjI6zJZQf8atFqV/UrBzIKrBfvN63KIwopBK3cGahCmBPU2InjA8Fsmh6AbzuBX+NlY2hMtRgsXm2LSZn96Imx2sXgQ/mflOrk1d3I4c4mewGrcIJwszgYG026uu16RotgXIXB33n47w1c7X18W++sPt1TplevYgm0d1Pv71GoBnzSvSlCsTL6WeGlOtWeqFFbjKek9ZhX8Y2Xpis5L5ayszNMQQ="
  on:
    branch: master
    repo: "Infinite-Loops-Firehose/chess"
  run: "rake db:migrate"
  skip_cleanup: true
  