language: ruby
rvm:
- 2.4.1
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake --trace db:create
- RAILS_ENV=test bundle exec rake --trace db:migrate
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
- bundle exec rubocop --config .rubocop.yml
deploy:
  provider: heroku
  api_key:
    secure: WTzZWZUb5dM2rXYu/Suqs9OhIi2WsET/bX9kGMuLNhV5emMowvHeLtFzQeCXxCbkeb+Hcbsc/pw6PectzlfDXe/42ydOfuLlHTm8G39sR2LzV/YTE+CTJ8RLA6d94MryNBbnpC5QdYpAklkIflR4ZECIcyqJjdaIKGClOF2QGin8BOhRDHiu2nAh8cnGd/8OT15x1ZvYNIQxqtFr/H0l/fNgUPDbuiCvh4rR2HRhXNDUB3CsvZhuUeoyDabbp1HXRIDxE8z389isRH7zOHJ82nY231536isEZ+Da65EqOAloZVDxrttWzR9SkzueTunTQFNNR2g0aQaNRWBJ4AvA3z75PP3nagZXFxiSJRv2XUPmFYWIDEb0gflh86LMUFb6DGWMiIh9GJwBx0wzPXf4uTHOMJxT7YPGddkK64GTHoloL/KnAqtyvgfte4csCXFqKnO3D5MRSrfI4AWpW5bQUzcwFdAVNqOvhKe+bKWJ/EKABfM42sE5IS4Me/jxo26lpkwN/weLVV8CkGlYoytr9Z7LI0OtIUdktiHCg7vwsonbsFuMDXaCXPFaAeGZRVlzGnnmcCnTZdUKyoaHBc/Lokch8GBVLo/zFze7XYhtYcXcmEm3xdn6trKI2s1FBq6aGa1GMSU7Lw7PuXPMeiXdA70QNOVg3GZEf87/A10vJGQ=
  app: infinite-loops-chess
  on:
    repo: Infinite-Loops-Firehose/chess
  run:
    - "rake db:migrate"
    - restart
  branches:
    only:
      - dennis
