development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:9e8f9e6c63ccfcf43d7891b8877a172d@crestfish.redistogo.com:11064/
  # redis://localhost:6379/1
  # new comment to push to heroku
